# Generated by Django 3.2.8 on 2021-10-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auth',
        ),
    ]
